import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Lifecycle} from '../server/lifecycle.mjs';import {Archive} from '../server/archive.mjs';import {validateCommand} from '../server/gateway.mjs';
const id='30699b54-cdb3-4eab-9e7b-a9db3e24ce07';
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pi-lifecycle-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const inv={workspaces:[{id:'w',path:'/project',hostId:'local'}],terminals:[],allTerminalIds:[],omittedHostIds:[],truncated:false};let owners=[],launches=0,closed=[];const options={dataDir:dir,inventory:async()=>inv,owners:()=>owners,launch:async(w,s)=>{assert.equal(w.id,'w');assert.equal(s,id);launches++;return 'term-owned';},close:async handle=>closed.push(handle)};return {dir,inv,options,setOwners:x=>owners=x,get launches(){return launches;},closed};}
test('new session launch is single-flight and durable across restart',async t=>{const f=fixture(t),life=new Lifecycle(f.options);const result=await Promise.all([life.create(id,'w'),life.create(id,'w')]);assert.equal(f.launches,1);assert.equal(result[0].sessionId,id);assert.deepEqual(result[0],result[1]);assert.equal((await new Lifecycle(f.options).create(id,'w')).reused,true);assert.equal(f.launches,1);});
test('uncertain launch is fenced and unknown/remote/incomplete workspaces never launch',async t=>{const f=fixture(t);let life=new Lifecycle(f.options);await assert.rejects(life.create(id,'unknown'),/не найдено/);f.inv.truncated=true;await assert.rejects(life.create(id,'w'),/неполный/);f.inv.truncated=false;f.inv.workspaces[0].hostId='remote';await assert.rejects(life.create(id,'w'),/не найдено/);f.inv.workspaces[0].hostId='local';life=new Lifecycle({...f.options,launch:async()=>{throw Error('timeout');}});await assert.rejects(life.create(id,'w'),/timeout/);await assert.rejects(new Lifecycle(f.options).create(id,'w'),/неизвестен/);assert.equal(f.launches,0);});
test('closing targets only current visible owner and running Pi requires explicit force',async t=>{const f=fixture(t),life=new Lifecycle(f.options);f.setOwners([{id,terminalId:'term-owned',status:'running'}]);await assert.rejects(life.close(id,true),/больше не открыта/);f.inv.terminals=[{id:'term-owned'}];await assert.rejects(life.close(id),/Подтверди/);await life.close(id,true);assert.deepEqual(f.closed,['term-owned']);await assert.rejects(life.close('unrelated',true),/не найден/);});
test('destructive commands require confirmation and do not accept terminal paths',()=>{const base={sessionId:id,requestId:'r'};for(const command of ['delete','close'])assert.throws(()=>validateCommand({...base,command}));assert.deepEqual(validateCommand({...base,command:'close',confirm:true,terminalId:'other'}),{type:'command',command:'close',...base,confirm:true,force:false});assert.throws(()=>validateCommand({...base,command:'new',workspaceId:'bad\npath'}));});
test('archive deletion removes the actual validated file, refusing live or substituted sessions',async t=>{const f=fixture(t),file=path.join(f.dir,'saved.jsonl');const row={id:'saved',cwd:'/project',path:file,title:'Saved',modified:'2026-10-05',messageCount:1};fs.writeFileSync(file,JSON.stringify({type:'session',id:'saved',cwd:'/project'})+'\n');const archive=new Archive({...f.options,list:async()=>[row]});f.setOwners([{id:'saved'}]);await assert.rejects(archive.remove('saved'),/Сначала закрой/);assert.ok(fs.existsSync(file));f.setOwners([]);fs.writeFileSync(file,JSON.stringify({type:'session',id:'another',cwd:'/project'})+'\n');await assert.rejects(archive.remove('saved'),/identity changed/);fs.writeFileSync(file,JSON.stringify({type:'session',id:'saved',cwd:'/project'})+'\n');assert.equal((await archive.remove('saved')).type,'deleted');assert.equal(fs.existsSync(file),false);});
