import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {once} from 'node:events';import {WebSocket} from 'ws';
import {supportedTiers,observedTier,restoredTier,tierPayload,TIER_ENTRY} from '../extension/mobile-tier.ts';import mobile from '../extension/mobile.ts';import {createGateway,validateCommand} from '../server/gateway.mjs';
const model={provider:'openai-codex',api:'openai-codex-responses',id:'gpt-6-astra',name:'GPT-6 Astra',reasoning:true};
const pause=()=>new Promise(r=>setTimeout(r,130));
test('tier applies only to explicitly supported providers, without mutating payload or implicit defaults',()=>{const payload={model:'gpt-6-astra',service_tier:'flex',input:[]};assert.equal(tierPayload(payload,model,null),undefined);assert.deepEqual(tierPayload(payload,model,'fast'),{...payload,service_tier:'priority'});assert.equal(payload.service_tier,'flex');assert.equal(tierPayload(payload,{...model,provider:'third-party'},'fast'),undefined);assert.deepEqual(supportedTiers(model),['standard','fast']);assert.equal(observedTier('priority'),'fast');assert.equal(observedTier('default'),'standard');assert.equal(observedTier('auto'),null);});
test('tier persistence reads only selected branch custom entries and commands validate',()=>{assert.equal(restoredTier([{type:'custom',customType:TIER_ENTRY,data:{serviceTier:'fast'}},{type:'custom',customType:TIER_ENTRY,data:{serviceTier:'standard'}}]),'standard');assert.equal(restoredTier([]),null);const command={type:'command',command:'configure',sessionId:'s',requestId:'r',serviceTier:'fast'};assert.equal(validateCommand(command).serviceTier,'fast');assert.throws(()=>validateCommand({...command,serviceTier:'ultrafast'}));});
test('tier command changes the next provider payload, current request effort stays fixed, provider confirms actual tier',async t=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'pi-tier-')),gateway=await createGateway({dataDir:dir,port:0,orca:false});const oldSocket=process.env.PI_MOBILE_SOCKET;process.env.PI_MOBILE_SOCKET=gateway.socketPath;
 const handlers={},entries=[];let effort='high',idle=true;
 const ctx={mode:'tui',cwd:'/fixture',model,modelRegistry:{getAvailable:()=>[model]},isIdle:()=>idle,sessionManager:{getSessionId:()=> 'tier-session',getSessionFile:()=>'/fixture/session.jsonl',getBranch:()=>entries},ui:{setStatus:()=>{},notify:()=>{}}};
 const pi={events:{on:()=>{}},getCommands:()=>[],on:(name,handler)=>handlers[name]=handler,registerCommand:()=>{},getSessionName:()=> 'Fixture',getThinkingLevel:()=>effort,setThinkingLevel:value=>effort=value,appendEntry:(customType,data)=>entries.push({type:'custom',customType,data})};
 mobile(pi);t.after(async()=>{handlers.session_shutdown({},ctx);if(oldSocket===undefined)delete process.env.PI_MOBILE_SOCKET;else process.env.PI_MOBILE_SOCKET=oldSocket;await gateway.close();await rm(dir,{recursive:true,force:true});});handlers.session_start({},ctx);await pause();
 const ws=new WebSocket(`ws://127.0.0.1:${gateway.port}/ws`,{headers:{Authorization:'Bearer '+gateway.token}});await once(ws,'open');t.after(()=>ws.close());
 async function command(requestId,args){const result=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('ACK timeout')),3000);const callback=raw=>{const f=JSON.parse(raw);if(f.type==='ack'&&f.requestId===requestId){clearTimeout(timer);ws.off('message',callback);resolve(f);}};ws.on('message',callback);});ws.send(JSON.stringify({type:'command',command:'configure',sessionId:'tier-session',requestId,...args}));return result;}
 async function config(){return (await(await fetch(`http://127.0.0.1:${gateway.port}/api/sessions/tier-session`,{headers:{Authorization:'Bearer '+gateway.token}})).json()).configuration;}
 assert.equal((await command('tier-fast',{serviceTier:'fast'})).ok,true);assert.equal(entries.at(-1).data.serviceTier,'fast');
 idle=false;handlers.agent_start({},ctx);const payload={model:'gpt-6-astra',input:[],reasoning:{effort:'high'}};const changed=handlers.before_provider_request({payload},ctx);assert.equal(changed.service_tier,'priority');assert.equal(payload.service_tier,undefined);
 assert.equal((await command('effort-next',{thinkingLevel:'low'})).ok,true);await pause();let c=await config();assert.equal(c.thinkingLevel,'low');assert.equal(c.execution.thinkingLevel,'high');assert.equal(c.execution.tierConfirmed,false);
 handlers.provider_stream_event({model:model.id,provider:model.provider,data:{type:'response.created',response:{service_tier:'default'}}},ctx);await pause();c=await config();assert.equal(c.serviceTier,'fast');assert.equal(c.execution.serviceTier,'standard');assert.equal(c.execution.tierConfirmed,true);
 assert.equal((await command('tier-standard',{serviceTier:'standard'})).ok,true);assert.equal(handlers.before_provider_request({payload},ctx).service_tier,'default');
 handlers.session_tree({},ctx);assert.equal((await config()).serviceTiers.length,2);
});
