package ru.billyhargrove.pimobile.core;
import org.json.*;import java.net.URI;
/** Public release metadata only. Never trusts a gateway-provided URL or APK without a digest. */
public final class ReleaseUpdate {
 public final String version,url,sha256;public final long size;public final boolean preview;
 private ReleaseUpdate(String v,String u,String h,long s,boolean p){version=v;url=u;sha256=h;size=s;preview=p;}
 public static int compare(String a,String b){String[] x=a.replaceFirst("^v","").split("\\."),y=b.replaceFirst("^v","").split("\\.");for(int i=0;i<3;i++){int n=Integer.compare(Integer.parseInt(x[i]),Integer.parseInt(y[i]));if(n!=0)return n;}return 0;}
 public static ReleaseUpdate newest(JSONArray releases,String installed){ReleaseUpdate best=null;for(int i=0;i<releases.length();i++){JSONObject r=releases.optJSONObject(i);if(r==null||r.optBoolean("draft"))continue;String tag=r.optString("tag_name");if(!tag.matches("v?[0-9]{1,6}\\.[0-9]{1,6}\\.[0-9]{1,6}")||compare(tag,installed)<=0)continue;JSONArray assets=r.optJSONArray("assets");if(assets==null)continue;for(int j=0;j<assets.length();j++){JSONObject a=assets.optJSONObject(j);if(a==null||!a.optString("name").equals("Pi-Mobile-"+tag.replaceFirst("^v","")+".apk"))continue;String url=a.optString("browser_download_url"),digest=a.optString("digest");long size=a.optLong("size");if(!url.startsWith("https://github.com/billyhargroveofficial/pi-mobile/releases/download/"+tag+"/")||!digest.matches("sha256:[0-9a-f]{64}")||size<=0||size>32*1024*1024)continue;if(best==null||compare(tag,best.version)>0)best=new ReleaseUpdate(tag,url,digest.substring(7),size,r.optBoolean("prerelease"));}}return best;}
 public static boolean allowedDownload(String url){try{URI u=URI.create(url);String host=u.getHost();return "https".equals(u.getScheme())&&u.getUserInfo()==null&&(u.getPort()==-1||u.getPort()==443)&&("github.com".equals(host)||"release-assets.githubusercontent.com".equals(host)||"objects.githubusercontent.com".equals(host));}catch(Exception e){return false;}}
}
