import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {publicMessages} from '../contracts/agent-transcript.mjs';
const idOK=s=>typeof s==='string'&&/^[a-zA-Z0-9._:-]{1,160}$/.test(s);
const clip=(s,n=300)=>typeof s==='string'?s.slice(0,n):'';
const num=n=>Number.isFinite(Number(n))?Math.max(0,Number(n)):0;
const statuses=new Set(['running','queued','starting','waiting','completed','failed','cancelled','paused','unknown']);
function cleanAgent(a){return {id:clip(a.id,160),name:clip(a.name),description:clip(a.description,1000),parentId:clip(a.parentId,160),workflowId:clip(a.workflowId,160),phase:clip(a.phase),status:statuses.has(a.status)?a.status:'unknown',model:clip(a.model),thinkingLevel:clip(a.thinkingLevel,20),startedAt:num(a.startedAt),finishedAt:num(a.finishedAt),outputTokens:num(a.outputTokens),toolCalls:num(a.toolCalls),canInspect:a.canInspect===true,error:clip(a.error,1000)};}
export function cleanOrchestration(data){return {available:data?.available===true,liveAvailable:data?.liveAvailable===true,observedAt:num(data?.observedAt),truncated:data?.truncated===true||(data?.agents?.length||0)>200||(data?.workflows?.length||0)>50,agents:(Array.isArray(data?.agents)?data.agents:[]).filter(a=>idOK(a?.id)).slice(-200).map(cleanAgent),workflows:(Array.isArray(data?.workflows)?data.workflows:[]).filter(w=>idOK(w?.id)).slice(-50).map(w=>({id:clip(w.id,160),title:clip(w.title),description:clip(w.description,1000),status:statuses.has(w.status)?w.status:'unknown',startedAt:num(w.startedAt),finishedAt:num(w.finishedAt),agentCount:num(w.agentCount),completed:num(w.completed),error:clip(w.error,1000),phases:(Array.isArray(w.phases)?w.phases:[]).slice(0,40).map(p=>({title:clip(p.title),status:statuses.has(p.status)?p.status:'unknown',agentCount:num(p.agentCount),completed:num(p.completed)}))}))};}
export function cleanAgentDetail(data){if(!idOK(data?.agent?.id))throw Error('Invalid agent');return {agent:cleanAgent(data.agent),source:clip(data.source||'live',100),before:num(data.before),hasMore:data.hasMore===true,truncated:data.truncated===true||(data.messages?.length||0)>180,childCount:num(data.childCount),messages:(Array.isArray(data.messages)?data.messages:[]).slice(-180).filter(m=>['user','assistant','toolResult','custom'].includes(m?.role)).map(m=>({id:clip(m.id,200),role:m.role,text:clip(m.text,16000),images:[],turnId:clip(m.turnId||'agent',200),phase:m.phase==='work'?'work':'answer',toolName:clip(m.toolName,200),toolStatus:['running','done','error','interrupted','pending'].includes(m.toolStatus)?m.toolStatus:'done',preview:clip(m.preview,2000)}))};}
const encodeCwd=cwd=>cwd.replace(/^[/\\]+/,'').replace(/[:/\\]+/g,'-');

/** Fixed-root, read-only fallback for old Pi processes. Never executes workflow scripts. */
export class OrchestrationStore {
 constructor({dataDir,tmpRoot=path.join(os.tmpdir(),`pi-subagents-${process.getuid?.()??'user'}`)}={}){this.root=path.join(dataDir,'orchestration');this.tmpRoot=tmpRoot;this.cache=new Map();this.inflight=new Map();this.saved=new Map();this.writes=new Map();this.lastWrite=new Map();}
 async savedCatalog(meta){if(this.saved.has(meta.id))return this.saved.get(meta.id);try{const {file,size}=await this.safeFile(this.root,meta.id+'.json');if(size>2*1024*1024)return null;const doc=JSON.parse(await fs.readFile(file,'utf8'));if(doc.cwd!==meta.cwd)return null;const clean=cleanOrchestration(doc.data);clean.liveAvailable=false;for(const a of [...clean.agents,...clean.workflows])if(['running','queued','starting','waiting'].includes(a.status))a.status='unknown';this.saved.set(meta.id,clean);return clean;}catch{return null;}}
 record(meta,data){const id=meta.id;if(!idOK(id))return Promise.resolve(data);const prior=this.writes.get(id)||Promise.resolve();const run=prior.catch(()=>{}).then(()=>this.writeRecord(meta,data));this.writes.set(id,run);run.then(()=>{if(this.writes.get(id)===run)this.writes.delete(id);},()=>{if(this.writes.get(id)===run)this.writes.delete(id);});return run;}
 async writeRecord(meta,data){const prior=await this.savedCatalog(meta),merge=(old,next,limit)=>{const map=new Map((old||[]).map(a=>[a.id,{...a,status:['running','queued','starting','waiting'].includes(a.status)?'unknown':a.status}]));for(const a of next)map.set(a.id,a);return [...map.values()].slice(-limit);};const value=cleanOrchestration({...data,agents:merge(prior?.agents,data.agents,200),workflows:merge(prior?.workflows,data.workflows,50)});this.saved.set(meta.id,value);const serialized=JSON.stringify({cwd:meta.cwd,data:value});if(this.lastWrite.get(meta.id)===serialized)return value;await fs.mkdir(this.root,{recursive:true,mode:0o700});const file=path.join(this.root,meta.id+'.json'),temp=file+'.tmp';await fs.writeFile(temp,serialized,{mode:0o600});await fs.rename(temp,file);this.lastWrite.set(meta.id,serialized);return value;}
 async saveDetail(meta,data){const value=cleanAgentDetail(data);value.source='saved-recent';value.truncated=value.truncated||value.hasMore;value.hasMore=false;value.before=0;const dir=path.join(this.root,meta.id);await fs.mkdir(dir,{recursive:true,mode:0o700});const bytes=JSON.stringify(value);if(Buffer.byteLength(bytes)>2*1024*1024)return;const file=path.join(dir,value.agent.id+'.json');await fs.writeFile(file,bytes,{mode:0o600});const entries=await fs.readdir(dir);const stats=await Promise.all(entries.map(async name=>{const s=await fs.stat(path.join(dir,name));return {name,mtime:s.mtimeMs,size:s.size};}));let total=0,count=0;for(const x of stats.sort((a,b)=>b.mtime-a.mtime)){total+=x.size;count++;if(count>200||total>32*1024*1024)await fs.unlink(path.join(dir,x.name)).catch(()=>{});}}
 async savedDetail(meta,id){if(!idOK(meta.id)||!idOK(id))throw Error('Invalid owner');const {file,size}=await this.safeFile(path.join(this.root,meta.id),id+'.json');if(size>2*1024*1024)throw Error('Detail too large');const result=cleanAgentDetail(JSON.parse(await fs.readFile(file,'utf8')));if(['running','queued','starting','waiting'].includes(result.agent.status))result.agent.status='unknown';for(const m of result.messages)if(m.toolStatus==='running')m.toolStatus='interrupted';return result;}
 async safeFile(root,name){if(path.basename(name)!==name)throw Error('Invalid file');const canonical=await fs.realpath(root);const file=path.join(canonical,name),s=await fs.lstat(file);if(!s.isFile()||s.isSymbolicLink())throw Error('Not a regular file');if(await fs.realpath(file)!==file)throw Error('Invalid path');return {file,size:s.size,mtime:s.mtimeMs};}
 async tasks(meta){if(!idOK(meta.id)||typeof meta.cwd!=='string')throw Error('Invalid owner');const expected=path.join(this.tmpRoot,encodeCwd(meta.cwd),meta.id,'tasks');const root=await fs.realpath(this.tmpRoot),actual=await fs.realpath(expected);if(!actual.startsWith(root+path.sep)||actual!==path.join(root,encodeCwd(meta.cwd),meta.id,'tasks'))throw Error('Invalid task root');return actual;}
 async bounded(file,start,end){const handle=await fs.open(file,'r');try{const stat=await handle.stat();if(!stat.isFile())throw Error('Not a file');const buffer=Buffer.alloc(Math.max(0,end-start));const {bytesRead}=await handle.read(buffer,0,buffer.length,start);return buffer.subarray(0,bytesRead).toString('utf8');}finally{await handle.close();}}
 async fallbackDetail(meta,id,before=0,maxBytes=512*1024){if(!idOK(id))throw Error('Invalid agent');const dir=await this.tasks(meta),{file,size,mtime}=await this.safeFile(dir,id+'.output');const end=before>0?Math.min(before,size):size,start=Math.max(0,end-maxBytes),body=await this.bounded(file,start,end);let skip=start>0?body.indexOf('\n')+1:0;if(start>0&&skip===0)skip=body.length;let offset=start+Buffer.byteLength(body.slice(0,skip)),raw=[];for(const line of body.slice(skip).split('\n')){try{const e=JSON.parse(line);if(e.agentId===id&&e.message){raw.push({...e.message,timestamp:e.message.timestamp||e.timestamp,__offset:offset});}}catch{}offset+=Buffer.byteLength(line)+1;}
 let first=raw[0];if(start>0){try{const initial=await this.bounded(file,0,Math.min(size,8192));first=JSON.parse(initial.split('\n')[0]).message||first;}catch{}}const page=publicMessages(raw);for(const m of page.messages)if(m.id.startsWith('message:')||m.id.startsWith('image:')){const index=Number(m.id.split(':')[1]);m.id=m.id.split(':')[0]+':'+(raw[index]?.__offset??start+index);}
 const recent=raw.filter(m=>m.role==='assistant').at(-1),name=first?.role==='user'?String(first.content?.find?.(b=>b.type==='text')?.text||first.content||'Agent').slice(0,100):'Recorded agent';return {agent:{id,name,description:'Saved transcript · live status unavailable',parentId:'',workflowId:'',status:'unknown',model:recent?.provider&&recent?.model?recent.provider+'/'+recent.model:'',startedAt:0,finishedAt:0,outputTokens:0,toolCalls:0,canInspect:true},source:'saved-output',...page,before:page.hasMore?raw[Math.max(0,raw.length-60)]?.__offset||start:start,hasMore:page.hasMore||start>0,truncated:page.truncated||skip>0,childCount:0,updatedAt:mtime};}
 async fallback(meta){let dir;try{dir=await this.tasks(meta);}catch{return {available:false,liveAvailable:false,agents:[],workflows:[],observedAt:Date.now(),truncated:false};}const names=await fs.readdir(dir);const files=names.filter(n=>/^[a-zA-Z0-9._:-]+\.output$/.test(n)).sort().slice(-200),agents=[];for(const file of files){try{const detail=await this.fallbackDetail(meta,file.slice(0,-7),0,32*1024);agents.push(detail.agent);}catch{}}
 return {available:true,liveAvailable:false,observedAt:Date.now(),agents,workflows:[],truncated:names.filter(n=>n.endsWith('.output')).length>200};}
 async catalog(meta){const key=meta.id+'\0'+meta.cwd,old=this.cache.get(key);if(old&&Date.now()-old.at<3000)return old.value;if(this.inflight.has(key))return this.inflight.get(key);const pending=(async()=>await this.savedCatalog(meta)||await this.fallback(meta))().then(value=>{this.cache.set(key,{at:Date.now(),value});if(this.cache.size>100)this.cache.delete(this.cache.keys().next().value);return value;}).finally(()=>this.inflight.delete(key));this.inflight.set(key,pending);return pending;}
}
