package ru.billyhargrove.pimobile;

import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.*;
import com.google.android.material.button.MaterialButton;
import org.json.*;
import java.util.*;
import ru.billyhargrove.pimobile.core.*;
import ru.billyhargrove.pimobile.net.AppExecutors;
import ru.billyhargrove.pimobile.ui.*;

/** Read-only list → workflow → nested agent conversation. Never attaches a Pi command listener. */
public final class OrchestrationActivity extends AppCompatActivity {
 private String session,workflow,agent;private PiApp app;private final Handler handler=new Handler(Looper.getMainLooper());private boolean started,busy,loaded;private int generation;
 private TextView subtitle,notice;private ProgressBar progress;private RecyclerView list;private MaterialButton older,children;private OrchestrationAdapter cards;private MessageAdapter messages;private long before;private boolean historyInitialized;private String transcriptSource="";private final LinkedHashMap<String,ChatMessage> transcript=new LinkedHashMap<>();
 private final Runnable poll=()->refresh(false);
 public static Intent intent(Context c,String session,String kind,String id,String title){return new Intent(c,OrchestrationActivity.class).putExtra("session",session).putExtra("workflow","workflow".equals(kind)?id:"").putExtra("agent","agent".equals(kind)?id:"").putExtra("title",title);}
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private TextView text(int size,int color){TextView v=new TextView(this);v.setTextSize(size);v.setTextColor(getColor(color));return v;}
 @Override public void onCreate(Bundle state){super.onCreate(state);app=PiApp.get(this);session=getIntent().getStringExtra("session");workflow=getIntent().getStringExtra("workflow");agent=getIntent().getStringExtra("agent");if(session==null)session="";if(workflow==null)workflow="";if(agent==null)agent="";
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(getColor(R.color.bg));LinearLayout top=new LinearLayout(this);top.setPadding(dp(16),dp(8),dp(16),dp(8));top.setGravity(Gravity.CENTER_VERTICAL);MaterialButton back=(MaterialButton)getLayoutInflater().inflate(R.layout.icon_button,top,false);back.setIconResource(R.drawable.ic_back);back.setContentDescription("Back");back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout headings=new LinearLayout(this);headings.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(0,-2,1);hp.setMargins(dp(12),0,dp(8),0);top.addView(headings,hp);TextView title=text(19,R.color.text_primary);title.setText(getIntent().getStringExtra("title"));title.setMaxLines(2);title.setEllipsize(android.text.TextUtils.TruncateAt.END);title.setTypeface(null,android.graphics.Typeface.BOLD);headings.addView(title);subtitle=text(12,R.color.text_secondary);subtitle.setText(agent.isEmpty()?"Workflows & agents":"Agent conversation · read-only");subtitle.setSingleLine(true);HorizontalScrollView detailScroll=new HorizontalScrollView(this);detailScroll.setHorizontalScrollBarEnabled(false);detailScroll.addView(subtitle,new HorizontalScrollView.LayoutParams(-2,-2));headings.addView(detailScroll,new LinearLayout.LayoutParams(-1,-2));MaterialButton refresh=(MaterialButton)getLayoutInflater().inflate(R.layout.icon_button,top,false);refresh.setIconResource(R.drawable.ic_refresh);refresh.setContentDescription("Refresh orchestration");refresh.setOnClickListener(v->refresh(false));top.addView(refresh,new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(top,new LinearLayout.LayoutParams(-1,-2));
  notice=text(12,R.color.text_secondary);notice.setId(R.id.orchestrationNotice);notice.setPadding(dp(20),dp(8),dp(20),dp(8));notice.setVisibility(View.GONE);root.addView(notice);progress=new ProgressBar(this);progress.setContentDescription("Loading orchestration");LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(dp(32),dp(32));pp.gravity=Gravity.CENTER;pp.setMargins(0,dp(20),0,dp(20));root.addView(progress,pp);
  children=new MaterialButton(this,null,com.google.android.material.R.attr.materialButtonOutlinedStyle);children.setId(R.id.agentChildren);children.setText("View child agents");children.setVisibility(View.GONE);LinearLayout.LayoutParams childParams=new LinearLayout.LayoutParams(-1,-2);childParams.setMargins(dp(16),dp(4),dp(16),0);root.addView(children,childParams);
  older=new MaterialButton(this,null,com.google.android.material.R.attr.materialButtonOutlinedStyle);older.setId(R.id.agentLoadOlder);older.setText("Load earlier activity");older.setVisibility(View.GONE);older.setOnClickListener(v->refresh(true));LinearLayout.LayoutParams olderParams=new LinearLayout.LayoutParams(-1,-2);olderParams.setMargins(dp(16),dp(4),dp(16),0);root.addView(older,olderParams);
  list=new RecyclerView(this);list.setId(R.id.orchestrationList);list.setLayoutManager(new LinearLayoutManager(this));list.setItemAnimator(null);list.setClipToPadding(false);list.setPadding(0,dp(8),0,dp(24));root.addView(list,new LinearLayout.LayoutParams(-1,0,1));if(agent.isEmpty()){cards=new OrchestrationAdapter((kind,id,name,summary)->startActivity(intent(this,session,kind,id,name).putExtra("agentSummary",summary.toString())));list.setAdapter(cards);}else{messages=new MessageAdapter(app.mediaLoader(),null,null);list.setAdapter(messages);}setContentView(root);SystemInsets.apply(this,root,top,null,false);
  if(!agent.isEmpty()&&getIntent().hasExtra("agentSummary"))try{renderAgent(new JSONObject().put("agent",new JSONObject(getIntent().getStringExtra("agentSummary"))).put("messages",new JSONArray()),false);}catch(JSONException ignored){}
 }
 @Override public void onStart(){super.onStart();started=true;refresh(false);}
 @Override public void onStop(){stopUpdates();super.onStop();}
 void stopUpdates(){started=false;generation++;busy=false;handler.removeCallbacks(poll);if(older!=null)older.setEnabled(true);}
 @Override public void onDestroy(){if(messages!=null)messages.close();super.onDestroy();}
 private void refresh(boolean history){if(!started||busy||!app.settings().hasToken())return;handler.removeCallbacks(poll);busy=true;older.setEnabled(false);int expected=generation;String base=app.settings().baseUrl(),token=app.settings().token();long cursor=history?before:0;AppExecutors.io().execute(()->{JSONObject result=null;try{result=agent.isEmpty()?app.api().fetchOrchestration(base,token,session):app.api().fetchAgent(base,token,session,agent,cursor);}catch(Exception ignored){}JSONObject value=result;AppExecutors.main(()->{if(!started||generation!=expected)return;busy=false;older.setEnabled(true);progress.setVisibility(View.GONE);if(value==null){notice.setText(loaded?"Activity unavailable · showing last received details. Retrying…":"Activity unavailable. Update the gateway or try again.");notice.setVisibility(View.VISIBLE);}else{if(agent.isEmpty())render(value);else renderAgent(value,history);loaded=true;}handler.postDelayed(poll,2500);});});}
 public void render(JSONObject data){progress.setVisibility(View.GONE);loaded=true;String childFilter=getIntent().getStringExtra("parentAgent");JSONObject shown=data;
  if(childFilter!=null){try{shown=new JSONObject(data.toString());JSONArray array=new JSONArray();Set<String> descendants=new HashSet<>();descendants.add(childFilter);boolean changed;do{changed=false;for(JSONObject a:OrchestrationData.agents(data,null))if(descendants.contains(a.optString("parentId"))&&descendants.add(a.optString("id")))changed=true;}while(changed);for(JSONObject a:OrchestrationData.agents(data,null))if(!childFilter.equals(a.optString("id"))&&descendants.contains(a.optString("id"))){JSONObject copy=new JSONObject(a.toString());copy.put("workflowId","");array.put(copy);}shown.put("workflows",new JSONArray()).put("agents",array);}catch(JSONException ignored){}}
  cards.submit(shown,workflow);subtitle.setText(workflow.isEmpty()?OrchestrationData.summary(shown):"Workflow · "+OrchestrationData.agents(shown,workflow).size()+" agents");String message=data.optBoolean("truncated")?"Some activity is omitted by server safety limits.":cards.getItemCount()==0?(data.optBoolean("available")?"No agents have been recorded here yet.":"No saved subagent activity found for this session."):!data.optBoolean("liveAvailable")?"Saved activity · live workflow phases require the observer and an idle Pi reload.":"Read-only · updates automatically";notice.setText(message);notice.setVisibility(View.VISIBLE);
 }
 public void renderAgent(JSONObject data,boolean history){progress.setVisibility(View.GONE);JSONObject a=data.optJSONObject("agent");if(a==null){notice.setText("Agent details unavailable");notice.setVisibility(View.VISIBLE);return;}subtitle.setText(OrchestrationData.label(a.optString("status"))+" · "+OrchestrationData.details(a));boolean active=OrchestrationData.active(a.optString("status"));messages.sessionStatus(active?SessionStatus.RUNNING:SessionStatus.IDLE);String source=data.optString("source","live");if(!source.equals(transcriptSource)){transcript.clear();before=0;historyInitialized=false;transcriptSource=source;}boolean hadMessages=!transcript.isEmpty();List<ChatMessage> page=SnapshotParser.parseMessages(data.optJSONArray("messages"));boolean nearBottom=!list.canScrollVertically(1);LinearLayoutManager layout=(LinearLayoutManager)list.getLayoutManager();int first=layout.findFirstVisibleItemPosition();String anchor=messages.keyAt(first);View top=layout.findViewByPosition(first);int offset=top==null?0:top.getTop()-list.getPaddingTop();
  if(history){LinkedHashMap<String,ChatMessage> merged=new LinkedHashMap<>();for(ChatMessage m:page)merged.put(m.stableKey(),m);merged.putAll(transcript);transcript.clear();transcript.putAll(merged);}else for(ChatMessage m:page)transcript.put(m.stableKey(),m);
  messages.submit(new ArrayList<>(transcript.values()));if(history){int pos=messages.positionOf(anchor);if(pos>=0)layout.scrollToPositionWithOffset(pos,offset);}else if(nearBottom&&messages.size()>0)list.scrollToPosition(messages.size()-1);
  if(history||!historyInitialized||!hadMessages){historyInitialized=true;before=data.optLong("before");older.setVisibility(data.optBoolean("hasMore")?View.VISIBLE:View.GONE);}String message=!a.optString("error").isEmpty()?a.optString("error"):data.optBoolean("truncated")?"Some large or older records were shortened or omitted.":page.isEmpty()?"No transcript yet · the agent may be queued or its log may have expired.":source.startsWith("saved")?"Saved transcript · read-only":"Read-only · prompt, progress, tools & answer";notice.setText(message);notice.setVisibility(View.VISIBLE);int count=data.optInt("childCount");children.setVisibility(count>0?View.VISIBLE:View.GONE);children.setText("View child agents · "+count);children.setOnClickListener(v->startActivity(intent(this,session,"","","Child agents").putExtra("parentAgent",agent)));loaded=true;
 }
}
