package ru.billyhargrove.pimobile.ui;
import android.content.*;import android.content.pm.*;import android.net.Uri;import android.provider.Settings;import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;import androidx.appcompat.app.AlertDialog;import androidx.core.content.FileProvider;
import com.google.android.material.dialog.MaterialAlertDialogBuilder;import com.google.android.material.progressindicator.LinearProgressIndicator;
import okhttp3.*;import org.json.*;import java.io.*;import java.security.MessageDigest;import java.util.*;import java.util.concurrent.TimeUnit;
import ru.billyhargrove.pimobile.BuildConfig;import ru.billyhargrove.pimobile.core.ReleaseUpdate;import ru.billyhargrove.pimobile.net.AppExecutors;

/** Opt-in download/install. Automatic checks never install, send the Pi token, or interrupt a live session. */
public final class AppUpdates {
 private final AppCompatActivity activity;private final SharedPreferences prefs;private final OkHttpClient http=new OkHttpClient.Builder().followRedirects(false).followSslRedirects(false).connectTimeout(15,TimeUnit.SECONDS).readTimeout(40,TimeUnit.SECONDS).callTimeout(120,TimeUnit.SECONDS).build();
 private boolean busy,closed;private volatile boolean cancelled;private volatile Call call;private File pendingInstall;private AlertDialog dialog;
 public AppUpdates(AppCompatActivity a){activity=a;prefs=a.getSharedPreferences("updates",Context.MODE_PRIVATE);}
 public void check(boolean manual){if(busy||closed)return;long now=System.currentTimeMillis();if(!manual&&now-prefs.getLong("lastCheck",0)<6*60*60*1000)return;busy=true;if(manual)toast("Checking for updates…");
  AppExecutors.io().execute(()->{ReleaseUpdate update=null;String error=null;try{Request req=new Request.Builder().url("https://api.github.com/repos/billyhargroveofficial/pi-mobile/releases?per_page=40").header("Accept","application/vnd.github+json").header("User-Agent","Pi-Mobile/"+BuildConfig.VERSION_NAME).build();call=http.newCall(req);try(Response res=call.execute()){if(!res.isSuccessful())throw new IOException("GitHub returned HTTP "+res.code());if(res.body()==null)throw new IOException("Empty release response");String json=readBounded(res.body().byteStream(),1024*1024);update=ReleaseUpdate.newest(new JSONArray(json),BuildConfig.VERSION_NAME);}prefs.edit().putLong("lastCheck",now).apply();}catch(Exception e){error=e.getMessage();}ReleaseUpdate result=update;String failure=error;AppExecutors.main(()->{busy=false;if(closed)return;if(failure!=null){if(manual)toast("Update check failed: "+failure);return;}if(result==null){if(manual)toast("You are up to date · "+BuildConfig.VERSION_NAME);return;}if(!manual&&result.version.equals(prefs.getString("dismissed","")))return;offer(result);});});
 }
 private void offer(ReleaseUpdate update){dialog=new MaterialAlertDialogBuilder(activity).setTitle("Pi Mobile "+update.version).setMessage("A new "+(update.preview?"preview ":"")+"release is available ("+Math.round(update.size/1024.0/1024)+" MB).\n\nDownload, verify and open the Android installer? Your connection settings will be kept.").setNegativeButton("Later",(d,w)->prefs.edit().putString("dismissed",update.version).apply()).setPositiveButton("Download update",(d,w)->download(update)).show();}
 private void download(ReleaseUpdate update){if(busy)return;busy=true;cancelled=false;LinearLayout content=new LinearLayout(activity);content.setOrientation(LinearLayout.VERTICAL);int p=Math.round(24*activity.getResources().getDisplayMetrics().density);content.setPadding(p,p,p,p);LinearProgressIndicator progress=new LinearProgressIndicator(activity);progress.setMax(100);content.addView(progress);TextView label=new TextView(activity);label.setText("Downloading…");label.setPadding(0,p/2,0,0);content.addView(label);dialog=new MaterialAlertDialogBuilder(activity).setTitle("Updating Pi Mobile").setView(content).setNegativeButton("Cancel",(d,w)->cancelDownload()).create();dialog.setOnCancelListener(d->cancelDownload());dialog.show();
  AppExecutors.io().execute(()->{File apk=null;String failure=null;try{File dir=new File(activity.getCacheDir(),"updates");if(!dir.isDirectory()&&!dir.mkdirs())throw new IOException("Cannot create update directory");File partial=new File(dir,"download.part");apk=new File(dir,"update.apk");try{String url=update.url;Response response=null;for(int redirect=0;redirect<5;redirect++){if(!ReleaseUpdate.allowedDownload(url))throw new IOException("Untrusted download host");call=http.newCall(new Request.Builder().url(url).build());response=call.execute();if(response.code()>=300&&response.code()<400){String location=response.header("Location");response.close();if(location==null)throw new IOException("Missing redirect URL");url=location;response=null;continue;}break;}if(response==null)throw new IOException("Too many redirects");try(Response res=response){if(!res.isSuccessful()||res.body()==null)throw new IOException("Download failed: HTTP "+res.code());MessageDigest digest=MessageDigest.getInstance("SHA-256");try(InputStream input=res.body().byteStream();OutputStream output=new FileOutputStream(partial)){byte[] buffer=new byte[65536];long total=0;int n,last=-1;while((n=input.read(buffer))!=-1){if(cancelled)throw new IOException("Cancelled");total+=n;if(total>update.size)throw new IOException("Unexpected APK size");digest.update(buffer,0,n);output.write(buffer,0,n);int percent=(int)(100*total/update.size);if(percent!=last){last=percent;AppExecutors.main(()->{if(!closed){progress.setProgressCompat(percent,true);label.setText("Downloading · "+percent+"%");}});}}if(total!=update.size)throw new IOException("Incomplete APK download");}if(!hex(digest.digest()).equals(update.sha256))throw new IOException("APK checksum mismatch");}verifyPackage(partial);if(apk.exists()&&!apk.delete())throw new IOException("Cannot replace previous download");if(!partial.renameTo(apk))throw new IOException("Cannot save APK");}finally{partial.delete();}}catch(Exception e){failure=e.getMessage();apk=null;}File ready=apk;String error=failure;AppExecutors.main(()->{busy=false;if(closed)return;if(dialog!=null)dialog.dismiss();if(cancelled)return;if(error!=null){toast("Update failed: "+error);return;}pendingInstall=ready;install();});});
 }
 private void verifyPackage(File apk)throws Exception{PackageManager pm=activity.getPackageManager();int flags=android.os.Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES;PackageInfo candidate=pm.getPackageArchiveInfo(apk.getAbsolutePath(),flags),installed=pm.getPackageInfo(activity.getPackageName(),flags);if(candidate==null||!activity.getPackageName().equals(candidate.packageName)||androidx.core.content.pm.PackageInfoCompat.getLongVersionCode(candidate)<=androidx.core.content.pm.PackageInfoCompat.getLongVersionCode(installed))throw new IOException("Wrong package or non-newer APK");if(signers(candidate).isEmpty()||!signers(candidate).equals(signers(installed)))throw new IOException("APK signing certificate differs from this installation");}
 private static Set<String> signers(PackageInfo p)throws Exception{Set<String> out=new HashSet<>();Signature[] signatures=android.os.Build.VERSION.SDK_INT>=28?(p.signingInfo==null?new Signature[0]:p.signingInfo.getApkContentsSigners()):(p.signatures==null?new Signature[0]:p.signatures);for(Signature s:signatures)out.add(hex(MessageDigest.getInstance("SHA-256").digest(s.toByteArray())));return out;}
 public void resume(){if(pendingInstall!=null&&!closed&&activity.getPackageManager().canRequestPackageInstalls())install();}
 private void install(){if(pendingInstall==null)return;try{if(!activity.getPackageManager().canRequestPackageInstalls()){dialog=new MaterialAlertDialogBuilder(activity).setTitle("Allow app updates").setMessage("Enable installation from Pi Mobile on the next screen, then return here. Android will still ask you to confirm the update.").setNegativeButton("Later",null).setPositiveButton("Open settings",(d,w)->activity.startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+activity.getPackageName())))).show();return;}verifyPackage(pendingInstall);Uri uri=FileProvider.getUriForFile(activity,activity.getPackageName()+".updates",pendingInstall);Intent intent=new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);activity.startActivity(intent);pendingInstall=null;}catch(Exception e){toast("Cannot install update: "+e.getMessage());}}
 private void cancelDownload(){cancelled=true;Call c=call;if(c!=null)c.cancel();}
 public void close(){closed=true;cancelDownload();if(dialog!=null)dialog.dismiss();}
 private void toast(String text){Toast.makeText(activity,text,Toast.LENGTH_LONG).show();}
 private static String hex(byte[] bytes){StringBuilder out=new StringBuilder();for(byte b:bytes)out.append(String.format(Locale.ROOT,"%02x",b&255));return out.toString();}
 private static String readBounded(InputStream input,int max)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=input.read(buffer))!=-1){if(out.size()+n>max)throw new IOException("Release response too large");out.write(buffer,0,n);}return out.toString("UTF-8");}
}
