package ru.billyhargrove.pimobile.ui;
import android.content.Context;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.widget.*;import android.text.*;import com.google.android.material.dialog.MaterialAlertDialogBuilder;
import ru.billyhargrove.pimobile.R;
/** A private, persistent preference for the USER bubble only; foreground is selected for contrast. */
public final class BubbleColors {
 private BubbleColors(){}
 public static int color(Context c){return c.getSharedPreferences("appearance",Context.MODE_PRIVATE).getInt("userBubble",c.getColor(R.color.bubble_user));}
 public static int foreground(int color){return androidx.core.graphics.ColorUtils.calculateLuminance(color)>.179?Color.BLACK:Color.WHITE;}
 public static GradientDrawable background(Context c,int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(24*c.getResources().getDisplayMetrics().density);return d;}
 public static void show(Context context){LinearLayout root=new LinearLayout(context);root.setOrientation(LinearLayout.VERTICAL);int pad=Math.round(24*context.getResources().getDisplayMetrics().density);root.setPadding(pad,pad,pad,pad);TextView preview=new TextView(context);preview.setText("Your messages will look like this.");preview.setTextSize(16);preview.setPadding(pad,pad,pad,pad);root.addView(preview,new LinearLayout.LayoutParams(-1,-2));EditText hex=new EditText(context);hex.setSingleLine(true);hex.setHint("Hex color · #RRGGBB");hex.setText(String.format(java.util.Locale.ROOT,"#%06X",color(context)&0xffffff));root.addView(hex,new LinearLayout.LayoutParams(-1,-2));int[] selected={color(context)};
  Runnable paint=()->{preview.setBackground(background(context,selected[0]));preview.setTextColor(foreground(selected[0]));};paint.run();
  String[] names={"Blue","Gray","Green","Purple","Orange","Rose"};int[] palette={0xff2f5de5,0xff303030,0xff247653,0xff7450bd,0xffd89a4b,0xffb75079};
  for(int i=0;i<names.length;i++){final int value=palette[i];com.google.android.material.button.MaterialButton button=new com.google.android.material.button.MaterialButton(context);button.setText(names[i]);button.setBackgroundTintList(android.content.res.ColorStateList.valueOf(value));button.setTextColor(foreground(value));button.setOnClickListener(v->hex.setText(String.format(java.util.Locale.ROOT,"#%06X",value&0xffffff)));root.addView(button,new LinearLayout.LayoutParams(-1,Math.round(48*context.getResources().getDisplayMetrics().density)));}
  hex.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){if(s.toString().matches("#[0-9a-fA-F]{6}")){selected[0]=Color.parseColor(s.toString());hex.setError(null);paint.run();}}public void afterTextChanged(Editable e){}});
  ScrollView scroll=new ScrollView(context);scroll.addView(root);androidx.appcompat.app.AlertDialog dialog=new MaterialAlertDialogBuilder(context).setTitle("Your bubble color").setView(scroll).setNegativeButton("Cancel",null).setNeutralButton("Reset",(d,w)->context.getSharedPreferences("appearance",Context.MODE_PRIVATE).edit().remove("userBubble").apply()).setPositiveButton("Save",null).create();dialog.setOnShowListener(d->dialog.getButton(android.content.DialogInterface.BUTTON_POSITIVE).setOnClickListener(v->{if(!hex.getText().toString().matches("#[0-9a-fA-F]{6}")){hex.setError("Use #RRGGBB");return;}context.getSharedPreferences("appearance",Context.MODE_PRIVATE).edit().putInt("userBubble",selected[0]).apply();dialog.dismiss();}));dialog.show();
 }
}
