package ru.billyhargrove.pimobile.ui;
import android.content.Context;import android.content.res.ColorStateList;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import com.google.android.material.bottomsheet.BottomSheetDialog;import java.util.function.Consumer;import ru.billyhargrove.pimobile.R;import ru.billyhargrove.pimobile.core.CommandBuilder;
public final class DeliverySheet extends BottomSheetDialog {
 public DeliverySheet(Context c,CommandBuilder.Behavior current,Consumer<CommandBuilder.Behavior> select){super(c);float d=c.getResources().getDisplayMetrics().density;LinearLayout root=new LinearLayout(c);root.setOrientation(LinearLayout.VERTICAL);root.setPadding((int)(20*d),(int)(20*d),(int)(20*d),(int)(24*d));
  TextView title=new TextView(c);title.setText("While Pi is working");title.setTextSize(20);title.setTextColor(c.getColor(R.color.text_primary));title.setPadding(0,0,0,(int)(20*d));root.addView(title);
  for(CommandBuilder.Behavior mode:new CommandBuilder.Behavior[]{CommandBuilder.Behavior.FOLLOW_UP,CommandBuilder.Behavior.STEER}){
   boolean queue=mode==CommandBuilder.Behavior.FOLLOW_UP,selected=mode==current;LinearLayout row=new LinearLayout(c);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding((int)(16*d),0,(int)(16*d),0);GradientDrawable bg=new GradientDrawable();bg.setColor(c.getColor(selected?R.color.accent_soft:R.color.surface));bg.setCornerRadius(20*d);row.setBackground(bg);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,(int)(80*d));rp.bottomMargin=(int)(8*d);root.addView(row,rp);
   ImageView icon=new ImageView(c);icon.setImageResource(queue?R.drawable.ic_queue:R.drawable.ic_steer);icon.setImageTintList(ColorStateList.valueOf(c.getColor(R.color.text_primary)));row.addView(icon,new LinearLayout.LayoutParams((int)(24*d),(int)(24*d)));
   LinearLayout labels=new LinearLayout(c);labels.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.leftMargin=(int)(14*d);row.addView(labels,lp);TextView name=new TextView(c);name.setText(queue?"Queue":"Steer");name.setTextSize(16);name.setTextColor(c.getColor(R.color.text_primary));labels.addView(name);TextView hint=new TextView(c);hint.setText(queue?"After the current task finishes":"At the next agent step");hint.setTextSize(12);hint.setTextColor(c.getColor(R.color.text_secondary));labels.addView(hint);TextView check=new TextView(c);check.setText(selected?"✓":"");check.setTextSize(20);check.setTextColor(c.getColor(R.color.accent));row.addView(check,new LinearLayout.LayoutParams((int)(24*d),-2));row.setContentDescription(queue?"Queue next message":"Steer current task");row.setOnClickListener(v->{select.accept(mode);dismiss();});ExpressiveMotion.press(row);
  }
  setContentView(root);androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{v.setPadding((int)(20*d),(int)(20*d),(int)(20*d),(int)(16*d)+insets.getInsets(androidx.core.view.WindowInsetsCompat.Type.navigationBars()).bottom);return insets;});setOnShowListener(v->{getBehavior().setState(com.google.android.material.bottomsheet.BottomSheetBehavior.STATE_EXPANDED);androidx.core.view.ViewCompat.requestApplyInsets(root);});
 }
}
