package ru.billyhargrove.pimobile.ui;
import android.content.Context;import android.view.Gravity;import android.widget.*;import com.google.android.material.bottomsheet.*;import com.google.android.material.button.MaterialButton;import ru.billyhargrove.pimobile.R;
public final class MarkdownPreview extends BottomSheetDialog {
 private final MarkdownRenderer renderer;
 public MarkdownPreview(Context c,String path,String source,MarkdownRenderer.Links links){super(c);LinearLayout root=new LinearLayout(c);root.setOrientation(LinearLayout.VERTICAL);int p=(int)(16*c.getResources().getDisplayMetrics().density);root.setPadding(p,p,p,p);
  LinearLayout bar=new LinearLayout(c);bar.setGravity(Gravity.CENTER_VERTICAL);TextView title=new TextView(c);title.setText(path);title.setTextColor(c.getColor(R.color.text_primary));title.setTextSize(16);title.setMaxLines(2);bar.addView(title,new LinearLayout.LayoutParams(0,-2,1));MaterialButton close=new MaterialButton(c,null,com.google.android.material.R.attr.materialIconButtonFilledTonalStyle);close.setIconResource(R.drawable.ic_back);close.setContentDescription("Закрыть предпросмотр Markdown");close.setOnClickListener(v->dismiss());bar.addView(close,new LinearLayout.LayoutParams(p*3,p*3));root.addView(bar);
  ScrollView scroll=new ScrollView(c);TextView text=new TextView(c);text.setId(R.id.documentText);text.setTextColor(c.getColor(R.color.text_primary));text.setTextSize(16);text.setTextIsSelectable(true);text.setPadding(0,p,0,p);scroll.addView(text);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));root.setLayoutParams(new android.view.ViewGroup.LayoutParams(-1,(int)(c.getResources().getDisplayMetrics().heightPixels*.85f)));setContentView(root);setOnShowListener(d->{getBehavior().setState(BottomSheetBehavior.STATE_EXPANDED);getBehavior().setSkipCollapsed(true);});renderer=new MarkdownRenderer(c,links);renderer.render(text,source);setOnDismissListener(d->renderer.close());
 }
}
