package ru.billyhargrove.pimobile.ui;

import android.content.Context;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import androidx.recyclerview.widget.*;
import org.json.*;
import java.util.*;
import ru.billyhargrove.pimobile.R;
import ru.billyhargrove.pimobile.core.OrchestrationData;

/** Quiet, full-width drill-down cards. A phase is not a synthetic progress percentage. */
public final class OrchestrationAdapter extends RecyclerView.Adapter<OrchestrationAdapter.Holder> {
 public interface Open {void open(String kind,String id,String title,JSONObject summary);}
 private static final class Row {final String kind,id;final JSONObject data;Row(String kind,JSONObject data){this.kind=kind;this.data=data;this.id=data.optString("id");}String key(){return kind+":"+id;}}
 private List<Row> rows=new ArrayList<>();private final Open open;
 public OrchestrationAdapter(Open open){this.open=open;}
 public void submit(JSONObject data,String workflow){List<Row> next=new ArrayList<>();if(workflow.isEmpty())for(JSONObject w:OrchestrationData.objects(data.optJSONArray("workflows")))next.add(new Row("workflow",w));for(JSONObject a:OrchestrationData.agents(data,null))if(workflow.isEmpty()?a.optString("workflowId").isEmpty():workflow.equals(a.optString("workflowId")))next.add(new Row("agent",a));List<Row> old=rows;DiffUtil.DiffResult diff=DiffUtil.calculateDiff(new DiffUtil.Callback(){public int getOldListSize(){return old.size();}public int getNewListSize(){return next.size();}public boolean areItemsTheSame(int i,int j){return old.get(i).key().equals(next.get(j).key());}public boolean areContentsTheSame(int i,int j){return !"running".equals(next.get(j).data.optString("status"))&&old.get(i).data.toString().equals(next.get(j).data.toString());}});rows=next;diff.dispatchUpdatesTo(this);}
 public int getItemCount(){return rows.size();}
 static class Holder extends RecyclerView.ViewHolder {final LinearLayout card;final TextView eyebrow,title,description,meta,action;final LinearLayout phases;Holder(LinearLayout outer,LinearLayout card,TextView eyebrow,TextView title,TextView description,TextView meta,LinearLayout phases,TextView action){super(outer);this.card=card;this.eyebrow=eyebrow;this.title=title;this.description=description;this.meta=meta;this.phases=phases;this.action=action;}}
 private static int dp(Context c,int n){return Math.round(n*c.getResources().getDisplayMetrics().density);}
 private static TextView text(Context c,int sp,int color){TextView t=new TextView(c);t.setTextSize(sp);t.setTextColor(c.getColor(color));return t;}
 private static void add(LinearLayout parent,View child,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(parent.getContext(),top);parent.addView(child,p);}
 public Holder onCreateViewHolder(ViewGroup parent,int type){Context c=parent.getContext();LinearLayout outer=new LinearLayout(c);outer.setPadding(dp(c,16),dp(c,6),dp(c,16),dp(c,6));outer.setLayoutParams(new RecyclerView.LayoutParams(-1,-2));LinearLayout card=new LinearLayout(c);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(c,18),dp(c,16),dp(c,18),dp(c,14));GradientDrawable bg=new GradientDrawable();bg.setColor(c.getColor(R.color.surface));bg.setCornerRadius(dp(c,24));card.setBackground(bg);android.util.TypedValue ripple=new android.util.TypedValue();c.getTheme().resolveAttribute(android.R.attr.selectableItemBackground,ripple,true);card.setForeground(c.getDrawable(ripple.resourceId));card.setClickable(true);card.setFocusable(true);outer.addView(card,new LinearLayout.LayoutParams(-1,-2));TextView eyebrow=text(c,11,R.color.text_secondary),title=text(c,18,R.color.text_primary),description=text(c,13,R.color.text_secondary),meta=text(c,11,R.color.text_secondary),action=text(c,12,R.color.text_primary);title.setTypeface(null,Typeface.BOLD);title.setMaxLines(3);title.setEllipsize(android.text.TextUtils.TruncateAt.END);description.setMaxLines(2);description.setEllipsize(android.text.TextUtils.TruncateAt.END);LinearLayout phases=new LinearLayout(c);phases.setOrientation(LinearLayout.VERTICAL);add(card,eyebrow,0);add(card,title,8);add(card,description,6);add(card,phases,12);add(card,meta,10);add(card,action,14);return new Holder(outer,card,eyebrow,title,description,meta,phases,action);}
 public void onBindViewHolder(Holder h,int position){Row row=rows.get(position);JSONObject x=row.data;Context c=h.card.getContext();boolean flow=row.kind.equals("workflow");String status=x.optString("status"),title=x.optString("title",x.optString("name","Agent"));h.eyebrow.setText((flow?"WORKFLOW":"AGENT")+"   ·   "+OrchestrationData.label(status));h.eyebrow.setTextColor(c.getColor(status.equals("failed")?R.color.danger:status.equals("running")?R.color.dot_ok:status.equals("queued")?R.color.dot_warn:R.color.text_secondary));h.title.setText(title);String description=x.optString("error").isEmpty()?x.optString("description"):x.optString("error");h.description.setTextColor(c.getColor(x.optString("error").isEmpty()?R.color.text_secondary:R.color.danger));h.description.setText(description);h.description.setVisibility(description.isEmpty()||description.equals(title)?View.GONE:View.VISIBLE);h.phases.removeAllViews();JSONArray phases=x.optJSONArray("phases");if(flow&&phases!=null)for(int i=0;i<phases.length();i++){JSONObject phase=phases.optJSONObject(i);if(phase==null)continue;TextView label=text(c,12,R.color.text_secondary);label.setPadding(0,dp(c,4),0,dp(c,4));String ps=phase.optString("status");label.setText((ps.equals("completed")?"✓  ":ps.equals("running")?"●  ":"○  ")+phase.optString("title")+(phase.optInt("agentCount")>0?"   ·   "+phase.optInt("completed")+"/"+phase.optInt("agentCount")+" agents done":""));if(ps.equals("running"))label.setTextColor(c.getColor(R.color.text_primary));h.phases.addView(label);}
 h.phases.setVisibility(h.phases.getChildCount()>0?View.VISIBLE:View.GONE);String meta=flow?x.optInt("completed")+" of "+x.optInt("agentCount")+" agents done":OrchestrationData.details(x);if(!flow&&!x.optString("phase").isEmpty())meta=x.optString("phase")+(meta.isEmpty()?"":" · "+meta);if(!flow&&!x.optString("parentId").isEmpty())meta="↳ Child agent · "+meta;h.meta.setText(meta);h.meta.setVisibility(meta.isEmpty()?View.GONE:View.VISIBLE);h.action.setText(flow?"View stages & agents  ›":x.optBoolean("canInspect")?"Open conversation  ›":"View details  ›");h.card.setContentDescription((flow?"Workflow: ":"Agent: ")+title+", "+OrchestrationData.label(status));h.card.setOnClickListener(v->open.open(row.kind,row.id,title,x));}
}
