package ru.billyhargrove.pimobile.ui;
import android.content.Context;import android.content.res.ColorStateList;import android.widget.LinearLayout;import android.widget.TextView;import com.google.android.material.button.MaterialButton;import org.json.JSONArray;import ru.billyhargrove.pimobile.R;
/** Session-local Standard / priority request, not a promise of a provider's accepted tier. */
public final class TierToggle extends LinearLayout {
 private final MaterialButton standard,fast;private final TextView hint;private String value="standard";private boolean available;
 public TierToggle(Context c){super(c);setOrientation(VERTICAL);float d=c.getResources().getDisplayMetrics().density;LinearLayout row=new LinearLayout(c);standard=button(c,"Standard",R.id.tierStandard);fast=button(c,"Fast",R.id.tierFast);fast.setIconResource(R.drawable.ic_bolt);fast.setIconSize(Math.round(18*d));LayoutParams left=new LayoutParams(0,Math.round(48*d),1);left.setMarginEnd(Math.round(8*d));row.addView(standard,left);row.addView(fast,new LayoutParams(0,Math.round(48*d),1));addView(row);hint=new TextView(c);hint.setTextSize(11);hint.setTextColor(c.getColor(R.color.text_secondary));hint.setPadding(0,Math.round(8*d),0,0);addView(hint);standard.setOnClickListener(v->{value="standard";paint();});fast.setOnClickListener(v->{value="fast";paint();});}
 private MaterialButton button(Context c,String text,int id){MaterialButton b=new MaterialButton(c,null,com.google.android.material.R.attr.materialButtonOutlinedStyle);b.setId(id);b.setText(text);b.setTextSize(13);return b;}
 public void configure(JSONArray tiers,String preferred){available=false;if(tiers!=null)for(int i=0;i<tiers.length();i++)if("fast".equals(tiers.optString(i)))available=true;value="fast".equals(preferred)?"fast":"standard";setVisibility(available?VISIBLE:GONE);paint();}
 public String value(){return available?value:null;}
 @Override public void setEnabled(boolean enabled){super.setEnabled(enabled);if(standard!=null){standard.setEnabled(enabled);fast.setEnabled(enabled);}}
 private void paint(){Context c=getContext();for(MaterialButton b:new MaterialButton[]{standard,fast}){boolean selected=(b==fast)=="fast".equals(value);b.setBackgroundTintList(ColorStateList.valueOf(selected?c.getColor(R.color.surface_alt):android.graphics.Color.TRANSPARENT));b.setStrokeColor(ColorStateList.valueOf(c.getColor(selected?R.color.text_primary:R.color.outline_soft)));b.setTextColor(c.getColor(selected?R.color.text_primary:R.color.text_secondary));b.setIconTint(ColorStateList.valueOf(c.getColor(selected?R.color.text_primary:R.color.text_secondary)));b.setSelected(selected);b.setContentDescription(b.getText()+(selected?", selected":""));}hint.setText("fast".equals(value)?"Requests priority processing; subject to provider availability.":"Standard processing for this session.");}
}
