package ru.billyhargrove.pimobile.ui;
import android.content.Context;import android.util.AttributeSet;import android.graphics.*;import org.json.*;import androidx.appcompat.widget.AppCompatTextView;import ru.billyhargrove.pimobile.R;import ru.billyhargrove.pimobile.core.DurationText;
public final class WorkingBadge extends AppCompatTextView {
 private JSONObject metric;private boolean active;private final android.os.Handler handler=new android.os.Handler(android.os.Looper.getMainLooper());
 private final Runnable tick=new Runnable(){public void run(){label();if(active&&isAttachedToWindow())handler.postDelayed(this,1000);}};
 public WorkingBadge(Context c,AttributeSet a){super(c,a);setVisibility(GONE);int bg=c.getColor(R.color.bg);setBackground(new android.graphics.drawable.GradientDrawable(android.graphics.drawable.GradientDrawable.Orientation.TOP_BOTTOM,new int[]{bg&0x00ffffff,bg,bg}));setClickable(false);setFocusable(false);}
 public void update(JSONObject frame){String id=frame.optString("activeTurnId","");active=!id.isEmpty();JSONArray stats=frame.optJSONArray("turns");JSONObject best=null;if(stats!=null)for(int i=0;i<stats.length();i++){JSONObject s=stats.optJSONObject(i);if(s==null)continue;if(active&&id.equals(s.optString("id"))){best=s;break;}if(!active&&(best==null||s.optLong("startedAt")>best.optLong("startedAt")))best=s;}metric=best;handler.removeCallbacks(tick);tick.run();}
 private void label(){if(!active&&metric==null){setVisibility(GONE);return;}setVisibility(VISIBLE);String text=active?"Working":"Worked";if(metric!=null&&metric.optLong("startedAt")>0){long end=metric.optLong("finishedAt");text+=" · "+DurationText.format((end>0?end:System.currentTimeMillis())-metric.optLong("startedAt"));}setText(text);invalidate();}
 @Override protected void onAttachedToWindow(){super.onAttachedToWindow();handler.removeCallbacks(tick);tick.run();}
 @Override protected void onDetachedFromWindow(){handler.removeCallbacks(tick);super.onDetachedFromWindow();}
 @Override protected void onDraw(Canvas c){if(active&&ExpressiveMotion.enabled()){float w=Math.max(1,getWidth()),x=((android.os.SystemClock.uptimeMillis()%2000)/2000f*2-.5f)*w;int base=getContext().getColor(R.color.text_secondary);getPaint().setShader(new LinearGradient(x-w*.3f,0,x+w*.3f,0,new int[]{base,Color.WHITE,base},null,Shader.TileMode.CLAMP));super.onDraw(c);getPaint().setShader(null);if(isShown())postInvalidateDelayed(40);}else super.onDraw(c);}
}
