package ru.billyhargrove.pimobile.ui;

import android.content.Context;import android.graphics.*;import android.view.*;import android.widget.*;
import androidx.recyclerview.widget.*;import java.util.*;import ru.billyhargrove.pimobile.R;import ru.billyhargrove.pimobile.core.ChatMessage;

/** Content-sized nested log, capped at 200dp; overflow scrolls inside the bubble. */
public final class WorkLogView extends FrameLayout {
 private final LogList list;private final LinearLayoutManager layout;private final Rows adapter=new Rows();private final View fade;private final MarkdownRenderer markdown;
 private List<ChatMessage> messages=new ArrayList<>();private String turn="";private long revision;private final Map<String,Anchor> anchors=new HashMap<>();
 private static final class Anchor{String id;int offset;boolean bottom;Anchor(String i,int o,boolean b){id=i;offset=o;bottom=b;}}
 public WorkLogView(Context c,MarkdownRenderer markdown){super(c);this.markdown=markdown;list=new LogList(c);list.setId(R.id.workLogList);layout=new LinearLayoutManager(c);list.setLayoutManager(layout);list.setAdapter(adapter);list.setItemAnimator(null);list.setOverScrollMode(OVER_SCROLL_NEVER);list.setPadding(0,0,0,dp(6));addView(list,new LayoutParams(-1,LayoutParams.WRAP_CONTENT));
  fade=new View(c){Paint p=new Paint();@Override protected void onDraw(Canvas canvas){int rgb=getContext().getColor(R.color.bubble_tool);p.setShader(new LinearGradient(0,0,0,getHeight(),rgb,rgb&0xffffff,Shader.TileMode.CLAMP));canvas.drawRect(0,0,getWidth(),getHeight(),p);}};fade.setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);fade.setVisibility(GONE);addView(fade,new LayoutParams(-1,dp(24),Gravity.TOP));
  list.addOnScrollListener(new RecyclerView.OnScrollListener(){@Override public void onScrolled(RecyclerView v,int x,int y){fade.setVisibility(v.canScrollVertically(-1)?VISIBLE:GONE);saveAnchor();}});
 }
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private void saveAnchor(){int first=layout.findFirstVisibleItemPosition();if(first<0||first>=messages.size()||turn.isEmpty())return;View top=layout.findViewByPosition(first);anchors.put(turn,new Anchor(messages.get(first).stableKey(),top==null?0:top.getTop(),!list.canScrollVertically(1)));}
 public void submit(String id,List<ChatMessage> source){saveAnchor();boolean same=turn.equals(id);Anchor saved=anchors.get(id);List<ChatMessage> old=messages,next=source==null?Collections.emptyList():new ArrayList<>(source);turn=id;final long version=++revision;
  DiffUtil.DiffResult diff=DiffUtil.calculateDiff(new DiffUtil.Callback(){public int getOldListSize(){return old.size();}public int getNewListSize(){return next.size();}public boolean areItemsTheSame(int a,int b){return same&&old.get(a).stableKey().equals(next.get(b).stableKey());}public boolean areContentsTheSame(int a,int b){return old.get(a).equals(next.get(b));}});messages=next;diff.dispatchUpdatesTo(adapter);
  if(saved==null||saved.bottom){if(!messages.isEmpty()){layout.scrollToPosition(messages.size()-1);list.post(()->{if(version==revision&&list.getScrollState()==RecyclerView.SCROLL_STATE_IDLE)list.scrollBy(0,1000000);});}}
  else for(int i=0;i<messages.size();i++)if(messages.get(i).stableKey().equals(saved.id)){layout.scrollToPositionWithOffset(i,saved.offset);break;}
  list.post(()->{if(version==revision)fade.setVisibility(list.canScrollVertically(-1)?VISIBLE:GONE);});
 }
 private class LogList extends RecyclerView{float lastY;LogList(Context c){super(c);setNestedScrollingEnabled(false);}
  @Override protected void onMeasure(int widthSpec,int heightSpec){int mode=MeasureSpec.getMode(heightSpec);int available=mode==MeasureSpec.UNSPECIFIED?dp(200):Math.min(dp(200),MeasureSpec.getSize(heightSpec));super.onMeasure(widthSpec,MeasureSpec.makeMeasureSpec(available,MeasureSpec.AT_MOST));}
  @Override public boolean dispatchTouchEvent(MotionEvent e){if(e.getActionMasked()==MotionEvent.ACTION_DOWN){lastY=e.getY();getParent().requestDisallowInterceptTouchEvent(true);}else if(e.getActionMasked()==MotionEvent.ACTION_MOVE){int direction=e.getY()<lastY?1:-1;getParent().requestDisallowInterceptTouchEvent(canScrollVertically(direction));lastY=e.getY();}return super.dispatchTouchEvent(e);}}
 private class Rows extends RecyclerView.Adapter<Item>{
  @Override public int getItemViewType(int p){return messages.get(p).role()==ChatMessage.Role.TOOL_RESULT?0:1;}
  @Override public Item onCreateViewHolder(ViewGroup parent,int type){LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.CENTER_VERTICAL);row.setLayoutParams(new RecyclerView.LayoutParams(-1,-2));Item h=new Item(row);if(type==0){row.setId(R.id.toolLine);row.setMinimumHeight(dp(20));h.icon=new ToolGlyph(getContext());row.addView(h.icon,new LinearLayout.LayoutParams(dp(13),dp(13)));h.name=new TextView(getContext());h.name.setTextSize(11);h.name.setIncludeFontPadding(false);h.name.setTypeface(Typeface.MONOSPACE);h.name.setTextColor(getContext().getColor(R.color.text_primary));h.name.setSingleLine();h.name.setMaxWidth(dp(105));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-2,-2);np.leftMargin=dp(5);row.addView(h.name,np);h.args=new FadeTextView(getContext());h.args.setId(R.id.workArguments);h.args.setTextSize(11);h.args.setIncludeFontPadding(false);h.args.setTextColor(getContext().getColor(R.color.text_secondary));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,-2,1);ap.leftMargin=dp(6);row.addView(h.args,ap);}else{h.text=new TextView(getContext());h.text.setId(R.id.messageText);h.text.setTextSize(13);h.text.setTextColor(getContext().getColor(R.color.text_primary));h.text.setPadding(0,dp(5),0,dp(7));row.addView(h.text,new LinearLayout.LayoutParams(-1,-2));}return h;}
  @Override public void onBindViewHolder(Item h,int p){ChatMessage m=messages.get(p);if(h.text!=null){markdown.render(h.text,m.text());return;}h.name.setText(m.toolName());h.icon.tool=m.toolName();h.icon.error="error".equals(m.toolStatus());h.icon.invalidate();String preview=m.preview();if(preview.isEmpty()){preview=m.text();int end=preview.indexOf('\n');if(end>=0)preview=preview.substring(0,end);}preview=ru.billyhargrove.pimobile.core.ToolArguments.format(m.toolName(),preview);h.args.setText(preview);h.itemView.setContentDescription(m.toolName()+", "+m.toolStatus()+", "+preview);}
  @Override public int getItemCount(){return messages.size();}
 }
 private static final class Item extends RecyclerView.ViewHolder{TextView name,text;FadeTextView args;ToolGlyph icon;Item(View v){super(v);}}
 private static final class ToolGlyph extends View{String tool="";boolean error;Paint p=new Paint(3);ToolGlyph(Context c){super(c);setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);}
  @Override protected void onDraw(Canvas c){super.onDraw(c);c.save();c.scale(getWidth()/24f,getHeight()/24f);p.setColor(getContext().getColor(error?R.color.danger:R.color.text_secondary));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.8f);p.setStrokeCap(Paint.Cap.ROUND);
   String n=tool.toLowerCase(Locale.ROOT);if(n.contains("bash")||n.contains("shell")){c.drawRoundRect(2,4,22,20,3,3,p);c.drawLine(6,9,9,12,p);c.drawLine(9,12,6,15,p);c.drawLine(12,15,17,15,p);}else if(n.contains("web")||n.contains("search")||n.contains("fetch")){c.drawCircle(12,12,9,p);c.drawOval(8,3,16,21,p);c.drawLine(3,12,21,12,p);}else if(n.equals("read")){c.drawRoundRect(5,2,19,22,2,2,p);c.drawLine(8,8,16,8,p);c.drawLine(8,12,16,12,p);c.drawLine(8,16,13,16,p);}else if(n.contains("edit")||n.contains("write")){c.drawLine(5,19,18,6,p);c.drawLine(5,19,9,18,p);c.drawLine(5,19,6,15,p);c.drawLine(16,4,20,8,p);}else if(n.contains("mcp")){c.drawRoundRect(5,8,19,17,3,3,p);c.drawLine(9,3,9,8,p);c.drawLine(15,3,15,8,p);c.drawLine(12,17,12,22,p);}else{c.drawRoundRect(3,4,21,20,3,3,p);c.drawLine(7,9,17,9,p);c.drawLine(7,14,14,14,p);}c.restore();}
 }
}
