#!/usr/bin/env bash
# Capture disposable synthetic UI evidence beside the immutable v0.6.003 baseline.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ADB="${ANDROID_HOME:-$HOME/Library/Android/sdk}/platform-tools/adb"
SERIAL="${1:-emulator-5554}"
OUT="${2:-$ROOT/artifacts/ui-migration}"
PKG=ru.billyhargrove.pimobile
FILES="/sdcard/Android/data/$PKG/files"
if [[ "$("$ADB" -s "$SERIAL" shell getprop ro.build.version.sdk | tr -d '\r')" != 35 ]]; then echo 'API35 emulator required' >&2; exit 2; fi
mkdir -p "$OUT"
"$ADB" -s "$SERIAL" install -r "$ROOT/android/app/build/outputs/apk/debug/app-debug.apk" >/dev/null
"$ADB" -s "$SERIAL" install -r "$ROOT/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" >/dev/null
run_test() {
 local output
 output="$("$ADB" -s "$SERIAL" shell am instrument -w -e class "$PKG.$1" "$PKG.test/androidx.test.runner.AndroidJUnitRunner")"
 printf '%s\n' "$output" > "$OUT/instrumentation-${1%%#*}.txt"
 if ! grep -Eq 'OK \([0-9]+ tests?\)' <<< "$output"; then printf '%s\n' "$output" >&2; echo 'Instrumentation did not report OK' >&2; exit 1; fi
}
pull() { "$ADB" -s "$SERIAL" pull "$FILES/$1" "$OUT/${2:-$1}" >/dev/null; }
run_test DesignPreviewTest
run_test OrchestrationUiTest
for file in usage-redesign.png settings-redesign.png tier-picker.png voice-recording.png attachment-thumbnail.png orchestration-overview.png orchestration-agents.png orchestration-conversation.png; do pull "$file"; done
pull chat-model-header.png header-single-line.png
# Narrow/large-font evidence is generated by the same synthetic orchestration fixture.
prior_size="$("$ADB" -s "$SERIAL" shell wm size | tr -d '\r' | awk '/Override size:/ {print $3}')"
prior_font="$("$ADB" -s "$SERIAL" shell settings get system font_scale | tr -d '\r')"
restore_display() {
 if [[ -n "$prior_size" ]]; then "$ADB" -s "$SERIAL" shell wm size "$prior_size" >/dev/null; else "$ADB" -s "$SERIAL" shell wm size reset >/dev/null; fi
 if [[ "$prior_font" == null || -z "$prior_font" ]]; then "$ADB" -s "$SERIAL" shell settings delete system font_scale >/dev/null; else "$ADB" -s "$SERIAL" shell settings put system font_scale "$prior_font" >/dev/null; fi
}
trap restore_display EXIT
"$ADB" -s "$SERIAL" shell wm size 945x2100 >/dev/null
"$ADB" -s "$SERIAL" shell settings put system font_scale 1.3 >/dev/null
run_test OrchestrationUiTest#workflowCardsShowRealPhasesAndOpenDrillDown
pull orchestration-overview.png overview-font130.png
printf 'Synthetic screenshots saved to %s; compare with docs/ui-baseline/v0.6.003/ (not pixel-identical across OS versions).\n' "$OUT"
