package ru.billyhargrove.pimobile;
import static org.junit.Assert.*;
import android.content.Context;
import androidx.test.core.app.ActivityScenario;import androidx.test.ext.junit.runners.AndroidJUnit4;import androidx.test.platform.app.InstrumentationRegistry;import androidx.test.uiautomator.*;
import org.junit.Test;import org.junit.runner.RunWith;import org.json.*;
@RunWith(AndroidJUnit4.class)
public class OrchestrationUiTest {
 private final Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();private final UiDevice device=UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
 private void idle(){InstrumentationRegistry.getInstrumentation().waitForIdleSync();device.waitForIdle();}
 private JSONObject fixture()throws Exception {return new JSONObject("{\"available\":true,\"liveAvailable\":true,\"workflows\":[{\"id\":\"wf_design\",\"title\":\"Polish the mobile experience\",\"description\":\"Independent review, implementation and verification\",\"status\":\"running\",\"agentCount\":4,\"completed\":2,\"phases\":[{\"title\":\"Explore\",\"status\":\"completed\",\"agentCount\":2,\"completed\":2},{\"title\":\"Build\",\"status\":\"running\",\"agentCount\":1,\"completed\":0},{\"title\":\"Verify\",\"status\":\"queued\",\"agentCount\":1,\"completed\":0}]}],\"agents\":[{\"id\":\"a\",\"workflowId\":\"wf_design\",\"name\":\"Map the event stream\",\"phase\":\"Explore\",\"status\":\"completed\",\"model\":\"openai-codex/gpt-6-sol\",\"canInspect\":true},{\"id\":\"b\",\"workflowId\":\"wf_design\",\"name\":\"Review navigation\",\"phase\":\"Explore\",\"status\":\"completed\",\"model\":\"openai-codex/gpt-6-sol\",\"canInspect\":true},{\"id\":\"c\",\"workflowId\":\"wf_design\",\"name\":\"Build workflow cards\",\"description\":\"Live status, phase hierarchy and nested conversations\",\"phase\":\"Build\",\"status\":\"running\",\"model\":\"openai-codex/gpt-6-sol\",\"thinkingLevel\":\"high\",\"outputTokens\":1840,\"canInspect\":true},{\"id\":\"d\",\"workflowId\":\"wf_design\",\"name\":\"Verify on a narrow screen\",\"phase\":\"Verify\",\"status\":\"queued\",\"canInspect\":false},{\"id\":\"standalone\",\"name\":\"Check accessibility\",\"status\":\"running\",\"description\":\"Touch targets, contrast and large text\",\"model\":\"openai-codex/gpt-6-sol\",\"canInspect\":true}]} ");}
 @Test public void workflowCardsShowRealPhasesAndOpenDrillDown()throws Exception{JSONObject data=fixture();try(ActivityScenario<OrchestrationActivity> scenario=ActivityScenario.launch(OrchestrationActivity.intent(context,"ui-fixture","","","Orchestration"))){scenario.onActivity(a->{a.stopUpdates();a.render(data);});idle();assertTrue(device.hasObject(By.text("Polish the mobile experience")));assertTrue(device.hasObject(By.textContains("2 of 4 agents done")));device.takeScreenshot(new java.io.File(context.getExternalFilesDir(null),"orchestration-overview.png"));device.findObject(By.descStartsWith("Workflow: Polish")).click();assertTrue(device.wait(Until.hasObject(By.text("Polish the mobile experience")),3000));device.pressBack();}}
 @Test public void workflowDetailShowsActiveCompletedAndQueuedAgents()throws Exception{JSONObject data=fixture();try(ActivityScenario<OrchestrationActivity> scenario=ActivityScenario.launch(OrchestrationActivity.intent(context,"ui-fixture","workflow","wf_design","Polish the mobile experience"))){scenario.onActivity(a->{a.stopUpdates();a.render(data);});idle();assertTrue(device.hasObject(By.text("Map the event stream")));assertTrue(device.hasObject(By.text("Build workflow cards")));device.takeScreenshot(new java.io.File(context.getExternalFilesDir(null),"orchestration-agents.png"));device.findObject(By.descStartsWith("Agent: Build workflow cards")).click();assertTrue(device.wait(Until.hasObject(By.text("Build workflow cards")),3000));device.pressBack();}}
 @Test public void childAgentsAreScopedToTheirParentAndOpenReadOnly()throws Exception{JSONObject data=fixture();data.getJSONArray("agents").put(new JSONObject().put("id","child").put("parentId","c").put("workflowId","wf_design").put("name","Inspect tool output").put("status","running").put("model","openai-codex/gpt-6-sol").put("canInspect",true));data.getJSONArray("agents").put(new JSONObject().put("id","other-child").put("parentId","b").put("name","Other branch").put("status","completed"));try(ActivityScenario<OrchestrationActivity> scenario=ActivityScenario.launch(OrchestrationActivity.intent(context,"ui-fixture","","","Child agents").putExtra("parentAgent","c"))){scenario.onActivity(a->{a.stopUpdates();a.render(data);});idle();assertTrue(device.hasObject(By.text("Inspect tool output")));assertFalse(device.hasObject(By.text("Other branch")));device.findObject(By.descStartsWith("Agent: Inspect tool output")).click();assertTrue(device.wait(Until.hasObject(By.text("Inspect tool output")),3000));device.pressBack();}}
 @Test public void agentConversationIsReadOnlyAndCanLoadEarlierActivity()throws Exception{JSONObject data=new JSONObject("{\"agent\":{\"id\":\"c\",\"name\":\"Build workflow cards\",\"status\":\"running\",\"model\":\"openai-codex/gpt-6-sol\",\"thinkingLevel\":\"high\",\"outputTokens\":1840},\"childCount\":1,\"hasMore\":true,\"before\":120,\"messages\":[{\"id\":\"u\",\"role\":\"user\",\"text\":\"Build a clear, live workflow view.\"},{\"id\":\"p\",\"role\":\"assistant\",\"phase\":\"work\",\"text\":\"I found the phase events. Now connecting the live cards.\"},{\"id\":\"t\",\"role\":\"toolResult\",\"toolName\":\"read\",\"toolStatus\":\"done\",\"preview\":\"{\\\"path\\\":\\\"src/workflow.ts\\\"}\",\"text\":\"Read 84 lines.\"},{\"id\":\"p2\",\"role\":\"assistant\",\"phase\":\"work\",\"text\":\"The workflow is updating without interrupting its agents.\"}]}");try(ActivityScenario<OrchestrationActivity> scenario=ActivityScenario.launch(OrchestrationActivity.intent(context,"ui-fixture","agent","c","Build workflow cards"))){scenario.onActivity(a->{a.stopUpdates();a.renderAgent(data,false);assertNull(a.findViewById(R.id.composerInput));assertNull(a.findViewById(R.id.stopButton));});idle();assertTrue(device.hasObject(By.textContains("I found the phase events")));assertTrue(device.hasObject(By.res(context.getPackageName(),"agentLoadOlder")));assertTrue(device.hasObject(By.res(context.getPackageName(),"agentChildren")));device.takeScreenshot(new java.io.File(context.getExternalFilesDir(null),"orchestration-conversation.png"));JSONObject earlier=new JSONObject(data.toString()).put("hasMore",false).put("before",0).put("messages",new JSONArray().put(new JSONObject().put("id","old").put("role","user").put("text","Earlier task context")));scenario.onActivity(a->a.renderAgent(earlier,true));assertTrue(device.wait(Until.gone(By.res(context.getPackageName(),"agentLoadOlder")),3000));}}
}
