package ru.billyhargrove.pimobile.core;
import org.junit.Test;import static org.junit.Assert.*;import org.json.*;
public class ConversationFramesTest {
 private JSONObject row(String id,String text)throws Exception{return new JSONObject().put("id",id).put("text",text);}
 private JSONObject snapshot()throws Exception{return new JSONObject().put("type","snapshot").put("sessionId","session").put("epoch",1).put("messages",new JSONArray().put(row("a","old")).put(row("b","remove")));}
 @Test public void mergesEditsDeletionsAndOrderWithoutDuplicates()throws Exception{JSONObject delta=new JSONObject().put("type","messages").put("messages",new JSONArray().put(row("a","new")).put(row("c","added"))).put("removedIds",new JSONArray().put("b")).put("order",new JSONArray().put("c").put("a"));JSONObject result=ConversationFrames.merge(snapshot(),delta);JSONArray rows=result.getJSONArray("messages");assertEquals(2,rows.length());assertEquals("c",rows.getJSONObject(0).getString("id"));assertEquals("new",rows.getJSONObject(1).getString("text"));assertEquals(result.toString(),ConversationFrames.merge(result,delta).toString());}
 @Test public void fullSnapshotReplacesStaleHistory()throws Exception{JSONObject fresh=snapshot().put("messages",new JSONArray());assertEquals(0,ConversationFrames.merge(snapshot(),fresh).getJSONArray("messages").length());}
 @Test public void historyPrependPreservesNewerLiveContentAndCheckpoint()throws Exception{JSONObject current=snapshot().put("checkpoint",new JSONObject().put("stream","gateway"));JSONObject history=new JSONObject().put("epoch",1).put("messages",new JSONArray().put(row("older","history")).put(row("a","stale")));JSONObject result=ConversationFrames.prepend(current,history);assertEquals(3,result.getJSONArray("messages").length());assertEquals("old",result.getJSONArray("messages").getJSONObject(1).getString("text"));assertEquals("gateway",result.getJSONObject("checkpoint").getString("stream"));assertSame(current,ConversationFrames.prepend(current,history.put("epoch",2)));}
}
