package ru.billyhargrove.pimobile.core;
import org.junit.Test;import static org.junit.Assert.*;import org.json.*;
public class ReleaseUpdateTest {
 private JSONObject release(String version,boolean preview)throws Exception{return new JSONObject().put("tag_name","v"+version).put("prerelease",preview).put("assets",new JSONArray().put(new JSONObject().put("name","Pi-Mobile-"+version+".apk").put("browser_download_url","https://github.com/billyhargroveofficial/pi-mobile/releases/download/v"+version+"/Pi-Mobile-"+version+".apk").put("digest","sha256:"+new String(new char[64]).replace('\0','a')).put("size",1000)));}
 private JSONObject asset(JSONObject r)throws Exception{return r.getJSONArray("assets").getJSONObject(0);}
 @Test public void supportsThreeDigitPatchVersions()throws Exception{assertEquals(0,ReleaseUpdate.compare("0.6.000","0.6.0"));assertTrue(ReleaseUpdate.compare("0.6.100","0.6.099")>0);ReleaseUpdate u=ReleaseUpdate.newest(new JSONArray().put(release("0.6.001",true)),"0.6.000");assertEquals("v0.6.001",u.version);}
 @Test public void comparesNumericVersions(){assertTrue(ReleaseUpdate.compare("v0.10.0","0.9.9")>0);assertEquals(0,ReleaseUpdate.compare("v1.0.0","1.0.0"));assertTrue(ReleaseUpdate.compare("2.0.0","1.999.999")>0);}
 @Test public void selectsNewestIncludingPreview()throws Exception{ReleaseUpdate u=ReleaseUpdate.newest(new JSONArray().put(release("0.6.0",true)).put(release("0.5.2",false)),"0.5.1");assertEquals("v0.6.0",u.version);assertTrue(u.preview);assertEquals(64,u.sha256.length());}
 @Test public void rejectsDraftAndInstalledVersions()throws Exception{assertNull(ReleaseUpdate.newest(new JSONArray().put(release("0.6.0",true).put("draft",true)).put(release("0.5.1",false)).put(release("0.4.0",false)),"0.5.1"));}
 @Test public void rejectsMissingOrInvalidDigest()throws Exception{for(String digest:new String[]{"","sha256:abc","md5:"+new String(new char[64]).replace('\0','a')}){JSONObject r=release("0.6.0",true);asset(r).put("digest",digest);assertNull(ReleaseUpdate.newest(new JSONArray().put(r),"0.5.1"));}}
 @Test public void rejectsUntrustedAssets()throws Exception{for(String url:new String[]{"https://evil.example/app.apk","https://github.com/other/pi-mobile/releases/download/v0.6.0/app.apk","http://github.com/billyhargroveofficial/pi-mobile/releases/download/v0.6.0/app.apk"}){JSONObject r=release("0.6.0",false);asset(r).put("browser_download_url",url);assertNull(ReleaseUpdate.newest(new JSONArray().put(r),"0.5.1"));}}
 @Test public void rejectsInvalidSizeAndName()throws Exception{for(long size:new long[]{0,-1,33554433L}){JSONObject r=release("0.6.0",false);asset(r).put("size",size);assertNull(ReleaseUpdate.newest(new JSONArray().put(r),"0.5.1"));}JSONObject r=release("0.6.0",false);asset(r).put("name","other.apk");assertNull(ReleaseUpdate.newest(new JSONArray().put(r),"0.5.1"));}
 @Test public void skipsMalformedReleaseRecords()throws Exception{JSONArray a=new JSONArray().put(JSONObject.NULL).put(new JSONObject().put("tag_name","v0.6.0-beta")).put(new JSONObject().put("tag_name","v9999999999.1.0")).put(release("0.6.0",true));assertEquals("v0.6.0",ReleaseUpdate.newest(a,"0.5.1").version);}
 @Test public void redirectAllowlistRejectsCredentialAndHostTricks(){assertTrue(ReleaseUpdate.allowedDownload("https://release-assets.githubusercontent.com/path?token=example"));assertTrue(ReleaseUpdate.allowedDownload("https://github.com:443/path"));for(String u:new String[]{"http://github.com/a","https://github.com.evil.test/a","https://github.com@evil.test/a","https://user@github.com/a","https://github.com:8443/a","file:///tmp/a","not a url"})assertFalse(u,ReleaseUpdate.allowedDownload(u));}
}
