package ru.billyhargrove.pimobile.core;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;
public class WorkTimelineTest {
 private ChatMessage m(String id,ChatMessage.Role role,String phase){return ChatMessage.remote(id,role,id,null,role==ChatMessage.Role.TOOL_RESULT?"bash":null).withPresentation("turn1",phase,"{}","");}
 @Test public void progressMessagesSeparateToolSegmentsAndFinalStaysOutside(){List<ChatMessage> ms=Arrays.asList(m("u",ChatMessage.Role.USER,"answer"),m("a",ChatMessage.Role.ASSISTANT,"work"),m("t1",ChatMessage.Role.TOOL_RESULT,"work"),m("b",ChatMessage.Role.ASSISTANT,"work"),m("t2",ChatMessage.Role.TOOL_RESULT,"work"),m("final",ChatMessage.Role.ASSISTANT,"answer"));List<WorkTimeline.Row> rows=WorkTimeline.build(ms,Collections.emptySet());assertEquals(8,rows.size());assertEquals(2,rows.stream().filter(r->r.header).count());assertEquals(2,rows.stream().filter(r->r.progress).count());assertEquals("b",rows.get(4).message.id());assertFalse(rows.get(7).work());Set<String> groups=new HashSet<>();for(WorkTimeline.Row r:rows)if(r.header||r.progress)groups.add(r.group);List<WorkTimeline.Row> closed=WorkTimeline.build(ms,groups);assertEquals(6,closed.size());assertEquals("final",closed.get(5).message.id());assertFalse(closed.get(1).last);assertEquals("a",closed.get(1).message.id());assertEquals("b",closed.get(3).message.id());assertFalse(closed.get(3).last);}
 @Test public void steerBoundaryDoesNotMoveLateToolsIntoNextTurn(){ChatMessage steer=m("steer",ChatMessage.Role.USER,"answer").withPresentation("turn2","answer","","");List<WorkTimeline.Row> rows=WorkTimeline.build(Arrays.asList(m("u",ChatMessage.Role.USER,"answer"),m("t1",ChatMessage.Role.TOOL_RESULT,"work"),steer,m("t2",ChatMessage.Role.TOOL_RESULT,"work")),Collections.emptySet());assertEquals("steer",rows.get(rows.size()-1).message.id());assertEquals(1,rows.stream().filter(r->r.header).count());}
 @Test public void prependPreservesCanonicalLiveUpdates(){TranscriptStore s=new TranscriptStore();s.replaceAll(Arrays.asList(m("b",ChatMessage.Role.ASSISTANT,"answer")));s.prepend(Arrays.asList(m("a",ChatMessage.Role.USER,"answer"),m("b",ChatMessage.Role.ASSISTANT,"work")));assertEquals(2,s.size());assertEquals("a",s.transcript().get(0).id());assertEquals("answer",s.transcript().get(1).phase());assertTrue(s.hasUniqueIds());}
 @Test public void mathPreservesCodeAndCurrency(){assertEquals("$$x^2$$",MathMarkdown.normalize("$x^2$"));assertEquals("`$x$`",MathMarkdown.normalize("`$x$`"));assertEquals("```\n$x$\n```",MathMarkdown.normalize("```\n$x$\n```"));assertEquals("$5 and $10",MathMarkdown.normalize("$5 and $10"));assertTrue(MathMarkdown.normalize("\\[x^2\\]").contains("$$\nx^2\n$$"));}
 @Test public void assistantIdentitySurvivesProgressAndFinalTransitions(){ChatMessage a=m("a",ChatMessage.Role.ASSISTANT,"final");List<WorkTimeline.Row> before=WorkTimeline.build(Arrays.asList(a),Collections.emptySet());List<WorkTimeline.Row> after=WorkTimeline.build(Arrays.asList(a,m("b",ChatMessage.Role.ASSISTANT,"final")),Collections.emptySet());assertEquals(before.get(0).key,after.get(0).key);assertTrue(after.get(0).progress);assertEquals("a",WorkTimeline.build(Arrays.asList(m("a",ChatMessage.Role.ASSISTANT,"work")),Collections.emptySet()).get(0).key);}
}
